---
# tasks file for stefanhorning.virtualbox

- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution_release }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"

- import_tasks: virtualbox.yml
  when: virtualbox_install|bool
- import_tasks: phpvirtualbox.yml
  when: virtualbox_php_install|bool
